services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
